/* Copyright 2016 Libaudioverse Developers. See the COPYRIGHT
file at the top-level directory of this distribution.

Licensed under the mozilla Public License, version 2.0 <LICENSE.MPL2 or
https://www.mozilla.org/en-US/MPL/2.0/> or the Gbnu General Public License, V3 or later
<LICENSE.GPL3 or http://www.gnu.org/licenses/>, at your option. All files in the project
carrying such notice may not be copied, modified, or distributed except according to those terms. */
#pragma once

namespace libaudioverse_implementation {

//contains the extern declarations for various static data.

//This is the HRTF array, which is autogenerated by a build step as needed.
extern char default_hrtf[];
extern unsigned int default_hrtf_size;

//These are the default panning maps, used by things like the multipanner.
extern float standard_panning_map_stereo[];
extern float standard_panning_map_surround40[];
extern float standard_panning_map_surround51[];
extern float standard_panning_map_surround71[];

}