import ctypes

libaudioverse_module = ctypes.cdll.LoadLibrary('build\libaudioverse.dll')

Lav_OBJTYPE_SINE = 6
Lav_OBJTYPE_GENERIC = 0
Lav_ERROR_INVALID_SLOT = 3
Lav_MAX_BLOCK_SIZE = 1024
Lav_ERROR_NO_OUTPUTS = 13
Lav_OBJTYPE_MIXER = 7
Lav_PROPERTYTYPE_STRING = 4
Lav_ERROR_CANNOT_INIT_AUDIO = 7
Lav_ERROR_MEMORY = 5
Lav_OBJTYPE_WORLD = 1
Lav_FILE_PITCH_BEND = -2
Lav_HRTF_ELEVATION = -2
Lav_ERROR_RANGE = 6
Lav_ATTENUATOR_MULTIPLIER = -1
Lav_SOURCE_DISTANCE_MODEL = -4
Lav_ERROR_NONE = 0
Lav_OBJTYPE_HRTF = 5
Lav_3D_POSITION = -2
Lav_OBJTYPE_SOURCE_MONO = 2
Lav_PROPERTYTYPE_INT = 1
Lav_ERROR_SHAPE = 11
Lav_ERROR_NULL_POINTER = 4
Lav_OBJTYPE_FILE = 4
Lav_ERROR_HRTF_INVALID = 10
Lav_3D_ORIENTATION = -1
Lav_OBJTYPE_HARD_LIMITER = 9
Lav_PROPERTYTYPE_DOUBLE = 3
Lav_DISTANCE_MODEL_LINEAR = 0
Lav_ERROR_CANNOT_CROSS_DEVICES = 12
Lav_ERROR_FILE_NOT_FOUND = 9
Lav_SOURCE_MAX_DISTANCE = -3
Lav_ERROR_LIMIT_EXCEEDED = 14
Lav_PROPERTYTYPE_FLOAT6 = 6
Lav_PROPERTYTYPE_FLOAT3 = 5
Lav_OBJTYPE_ZEROS = 3
Lav_ERROR_FILE = 8
Lav_ERROR_UNKNOWN = 1
Lav_OBJTYPE_ATTENUATOR = 8
Lav_SINE_FREQUENCY = -1
Lav_HRTF_AZIMUTH = -1
Lav_DISTANCE_MODEL_MAX = 0
Lav_DISTANCE_MODEL_MIN = 0
Lav_PROPERTYTYPE_FLOAT = 2
Lav_ERROR_TYPE_MISMATCH = 2
Lav_FILE_POSITION = -1


Lav_deviceGetOutputObject = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p))(('Lav_deviceGetOutputObject', libaudioverse_module))
Lav_initializeLibrary = ctypes.CFUNCTYPE(ctypes.c_int)(('Lav_initializeLibrary', libaudioverse_module))
Lav_createHardLimiterObject = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_uint, ctypes.POINTER(ctypes.c_void_p))(('Lav_createHardLimiterObject', libaudioverse_module))
Lav_getDoublePropertyRange = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.))(('Lav_getDoublePropertyRange', libaudioverse_module))
Lav_objectGetFloat3Property = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.))(('Lav_objectGetFloat3Property', libaudioverse_module))
Lav_objectGetFloat6Property = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.))(('Lav_objectGetFloat6Property', libaudioverse_module))
Lav_objectSetStringProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.c_char_p)(('Lav_objectSetStringProperty', libaudioverse_module))
Lav_createHrtfData = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p))(('Lav_createHrtfData', libaudioverse_module))
Lav_createWorld = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p))(('Lav_createWorld', libaudioverse_module))
Lav_getIntPropertyRange = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int))(('Lav_getIntPropertyRange', libaudioverse_module))
Lav_createHrtfObject = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p))(('Lav_createHrtfObject', libaudioverse_module))
Lav_createSource = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p))(('Lav_createSource', libaudioverse_module))
Lav_objectSetParent = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_uint, ctypes.c_void_p, ctypes.c_uint)(('Lav_objectSetParent', libaudioverse_module))
Lav_objectGetIntProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.c_int))(('Lav_objectGetIntProperty', libaudioverse_module))
Lav_objectSetFloat6Property = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes., ctypes., ctypes., ctypes., ctypes., ctypes.)(('Lav_objectSetFloat6Property', libaudioverse_module))
Lav_objectSetDoubleProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.)(('Lav_objectSetDoubleProperty', libaudioverse_module))
Lav_objectSetFloatProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.)(('Lav_objectSetFloatProperty', libaudioverse_module))
Lav_deviceGetBlock = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.POINTER(ctypes.))(('Lav_deviceGetBlock', libaudioverse_module))
Lav_createDefaultAudioOutputDevice = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.POINTER(ctypes.c_void_p))(('Lav_createDefaultAudioOutputDevice', libaudioverse_module))
Lav_getFloatPropertyRange = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.), ctypes.POINTER(ctypes.))(('Lav_getFloatPropertyRange', libaudioverse_module))
Lav_objectGetDoubleProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.))(('Lav_objectGetDoubleProperty', libaudioverse_module))
Lav_createAttenuatorObject = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_uint, ctypes.POINTER(ctypes.c_void_p))(('Lav_createAttenuatorObject', libaudioverse_module))
Lav_createReadDevice = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_uint, ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.c_void_p))(('Lav_createReadDevice', libaudioverse_module))
Lav_createMixerObject = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.c_void_p))(('Lav_createMixerObject', libaudioverse_module))
Lav_objectSetIntProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.c_int)(('Lav_objectSetIntProperty', libaudioverse_module))
Lav_deviceSetOutputObject = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p)(('Lav_deviceSetOutputObject', libaudioverse_module))
Lav_objectGetParent = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_uint, ctypes.POINTER(ctypes.c_void_p), ctypes.POINTER(ctypes.c_uint))(('Lav_objectGetParent', libaudioverse_module))
Lav_createSineObject = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.POINTER(ctypes.c_void_p))(('Lav_createSineObject', libaudioverse_module))
Lav_objectClearParent = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_uint)(('Lav_objectClearParent', libaudioverse_module))
Lav_objectGetFloatProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.))(('Lav_objectGetFloatProperty', libaudioverse_module))
Lav_objectGetStringProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes.POINTER(ctypes.c_char_p))(('Lav_objectGetStringProperty', libaudioverse_module))
Lav_objectGetOutputCount = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint))(('Lav_objectGetOutputCount', libaudioverse_module))
Lav_objectResetProperty = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int)(('Lav_objectResetProperty', libaudioverse_module))
Lav_objectGetInputCount = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.POINTER(ctypes.c_uint))(('Lav_objectGetInputCount', libaudioverse_module))
Lav_objectSetFloat3Property = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_int, ctypes., ctypes., ctypes.)(('Lav_objectSetFloat3Property', libaudioverse_module))
Lav_createFileObject = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_void_p, ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p))(('Lav_createFileObject', libaudioverse_module))
