== Building Libaudioverse

IMPORTANT:
While this page is platform-neutral, Libaudioverse currently only builds on Windows.
Overcoming this shortcoming will happen in short order.

=== Dependencies

All of the following dependencies are required to build Libaudioverse.

- Libsndfile
- CMake
- Python 2.7.x.

And the following Python packages:

- Numpy
- Scipy
- Jinja2
- Enum34 (for running the Python bindings only)
- Pycparser

For the documentation, you will also need a working implementation of Asciidoc and it must be callable as `asciidoc` at the command line.

=== Building

IMPORTANT: you must do an out-of-source build with CMake and it must be in `repository_root/build` where `repository_root` is the directory of the Libaudioverse repository.
Otherwise, binding and documentation generation will crash or do other unexpected things.

The rest of the process is the standard CMake process.
Something like the following:

....
mkdir build
cd build
cmake -G "MY_GENERATOR" ..
my_generator_specific_build_command
....

A custom target, `libaudioverse_docs`, generates a set of Asciidoc documentation in `build/documentation`.
The resulting manual is titled `libaudioverse_manual.html` and may be found, along with the manual's source files,  in the `documentation` subdirectory of the build directory.
Alternatively, you can continue reading this one.
